# config.yaml

# Configuración de rutas
rutas:
  datos_crudos: "../raw_data/CG-TEM-intestinal_prueba.xlsx"  # Ruta relativa al archivo de datos. 
                                          # Opciones:
                                          # 1. miR-9.xlsx: "Breast Cancer", Controles: "7BSC", Muestras: "3CM"
                                          # 2. miR-29.xlsx "Breast Cancer", Controles: "7BSC", Muestras: "3CM"
                                          # 3. CG-TEM-intestinal.xlsx "Gastric Cancer", Controles: "4GB", Muestras: "3CG"
                                          # 4. CG-TEM-difuso.xlsx "Gastric Cancer", Controles: "4GB", Muestras: "3CG"
                                          

  resultados_base: "../resultados"  # Carpeta base para todos los resultados

# Parámetros de análisis
analisis:
  contexto_biologico: "Cáncer y TEM"  # Opciones: "Cáncer y TEM", "Cáncer y micro RNAs"
  metodo_normalizacion: "gen de referencia"  # Opciones: "gen de referencia", "promedios"
  tipo_cancer: "Gastric Cancer"  # Opciones: "Breast Cancer", "Gastric Cancer"
  nombre_controles: "4GB" 
  nombre_muestras: "3CG"

# Configuración de Google Colab (opcional)
colab:
  montar_drive: false  # Cambiar a true si se usa Google Colab
  ruta_drive: "/content/drive/MyDrive"

